
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import {
  Wallet,
  Shield,
  Users,
  Lock,
  Clock,
  RefreshCw,
  Globe,
  BarChart3,
  Percent,
  CheckCircle2
} from 'lucide-react';

export function Features() {
  return (
    <div className="container mx-auto px-4 py-12">
      {/* Hero Section */}
      <div className="text-center max-w-3xl mx-auto mb-16">
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-4xl md:text-5xl font-bold mb-6"
        >
          Platform Features
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-xl text-slate-300"
        >
          Discover why thousands of users choose Starkord for their staking needs
        </motion.p>
      </div>

      {/* Main Features */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-24">
        {[
          {
            icon: Wallet,
            title: 'Easy Participation',
            description: 'Stake ETH and earn daily rewards without handling the technical aspects of staking.',
          },
          {
            icon: BarChart3,
            title: 'Automated Staking',
            description: 'Starkord manages staking across diversified crypto protocols and DeFi assets.',
          },
          {
            icon: Clock,
            title: 'Fixed-Term Yields',
            description: 'Daily rewards distributed for 180 days based on your stake amount.',
          },
          {
            icon: Shield,
            title: 'Risk Management',
            description: 'Comprehensive risk management practices and diversified staking strategies.',
          },
          {
            icon: Percent,
            title: 'Transparent Fees',
            description: 'Clear fee structure with only 10% performance fee on earned rewards.',
          },
          {
            icon: RefreshCw,
            title: 'Daily Restaking',
            description: 'Enhance your earnings by restaking rewards for compound growth.',
          },
          {
            icon: Users,
            title: 'Referral Program',
            description: 'Earn 10% of daily rewards generated by your referred users.',
          },
          {
            icon: Lock,
            title: 'Secure Platform',
            description: 'Industry-leading security measures protect your staked assets.',
          },
          {
            icon: Globe,
            title: 'Global Access',
            description: 'Available worldwide with 24/7 platform accessibility.',
          },
        ].map((feature, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 * index }}
            className="bg-slate-800/50 backdrop-blur-xl rounded-xl p-8 border border-slate-700/50 hover:border-blue-500/50 transition-all duration-200"
          >
            <feature.icon className="w-12 h-12 text-blue-400 mb-4" />
            <h3 className="text-xl font-bold mb-4">{feature.title}</h3>
            <p className="text-slate-400">{feature.description}</p>
          </motion.div>
        ))}
      </div>

      {/* Staking Plans */}
      <div className="mb-24">
        <h2 className="text-3xl font-bold text-center mb-12">Available Staking Plans</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {[
            {
              name: 'Core Vault',
              minStake: '0.05 ETH',
              yield: '1.5%',
              duration: '180 days',
              color: 'from-blue-500 to-blue-600',
              ideal: 'Entry-level users seeking stable returns'
            },
            {
              name: 'Growth Nexus',
              minStake: '2 ETH',
              yield: '2.5%',
              duration: '180 days',
              color: 'from-purple-500 to-purple-600',
              ideal: 'Balanced growth with moderate risk'
            },
            {
              name: 'Elite Matrix',
              minStake: '10 ETH',
              yield: '3.5%',
              duration: '180 days',
              color: 'from-emerald-500 to-emerald-600',
              ideal: 'Experienced stakers seeking higher returns'
            },
            {
              name: 'Legacy Protocol',
              minStake: '20 ETH',
              yield: '5%',
              duration: '180 days',
              color: 'from-amber-500 to-amber-600',
              ideal: 'Maximum returns for strategic investors'
            }
          ].map((plan, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 * index }}
              className={`bg-gradient-to-br ${plan.color} rounded-xl p-6 relative overflow-hidden group hover:scale-[1.02] transition-all duration-200`}
            >
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-3xl transform translate-x-16 -translate-y-16" />
              
              <h3 className="text-xl font-bold mb-4">{plan.name}</h3>
              
              <div className="space-y-3 mb-6">
                <div className="flex justify-between items-center">
                  <span className="text-white/80">Min Stake</span>
                  <span className="font-bold">{plan.minStake}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-white/80">Daily Yield</span>
                  <span className="font-bold">{plan.yield}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-white/80">Duration</span>
                  <span className="font-bold">{plan.duration}</span>
                </div>
              </div>
              
              <p className="text-sm text-white/80 mb-6">Ideal for: {plan.ideal}</p>
              
              <Link
                to="/login"
                className="block w-full bg-white/20 hover:bg-white/30 backdrop-blur-sm py-3 rounded-lg font-medium text-center transition-colors"
              >
                Start Staking
              </Link>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Security Section */}
      <div className="mb-24">
        <h2 className="text-3xl font-bold text-center mb-12">Security & Risk Management</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {[
            {
              title: 'Asset Protection',
              description: 'Your staked assets are protected by comprehensive security measures and risk management strategies.',
              features: [
                'Multi-signature wallets',
                'Cold storage security',
                'Regular security audits',
                'Insurance coverage'
              ]
            },
            {
              title: 'Risk Management',
              description: 'We employ robust risk management practices to protect your investments.',
              features: [
                'Diversified staking strategies',
                'Real-time monitoring',
                'Automated risk assessment',
                'Regular portfolio rebalancing'
              ]
            }
          ].map((section, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 * index }}
              className="bg-slate-800/50 backdrop-blur-xl rounded-xl p-8 border border-slate-700/50"
            >
              <h3 className="text-xl font-bold mb-4">{section.title}</h3>
              <p className="text-slate-400 mb-6">{section.description}</p>
              <ul className="space-y-2">
                {section.features.map((feature, featureIndex) => (
                  <li key={featureIndex} className="flex items-center text-slate-300">
                    <CheckCircle2 className="w-5 h-5 text-green-400 mr-2" />
                    {feature}
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>
      </div>

      {/* CTA Section */}
      <div className="text-center max-w-2xl mx-auto">
        <h2 className="text-3xl font-bold mb-4">Ready to Start Earning?</h2>
        <p className="text-slate-400 mb-8">
          Join thousands of satisfied users and start earning passive income today.
        </p>
        <Link
          to="/login"
          className="inline-block px-8 py-3 bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white rounded-lg font-medium transition-all duration-200"
        >
          Start Staking Now
        </Link>
      </div>
    </div>
  );
}